# is for Heading
# Python Class
## Python Class
# Python Class

*Class* - Single is to Italizise

**Class** is to Bold

In [ ]:
(-) is for bullet point
- Python
- Excel
- PowerBI
  - SQL
     - PowerQuery

RAW leaves things as it is.
# Python

In [5]:
g = 2345*4567
g

10709615

In [4]:
g

10709615

# Python data Structure
# List

In [6]:
w = ["Ada", 25, "Bianca", 18, "Victor", 28, "Godwin", 23]

In [7]:
w

['Ada', 25, 'Bianca', 18, 'Victor', 28, 'Godwin', 23]

In [8]:
type(w)

list

In [9]:
w.append("Aisha")

In [10]:
w.append(25)

In [11]:
w

['Ada', 25, 'Bianca', 18, 'Victor', 28, 'Godwin', 23, 'Aisha', 25]

In [13]:
w.extend(["James", 24])

In [14]:
w

['Ada', 25, 'Bianca', 18, 'Victor', 28, 'Godwin', 23, 'Aisha', 25, 'James', 24]

In [16]:
w.insert(3, "Bianca")

In [17]:
w.remove("Bianca")

In [19]:
w.pop(-1)

'James'

In [20]:
w.sort()

TypeError: '<' not supported between instances of 'int' and 'str'

In [21]:
len(w)

10

In [22]:
w

['Ada', 25, 'Bianca', 18, 'Victor', 28, 'Godwin', 23, 'Aisha', 25]

In [23]:
w.reverse()

In [24]:
w

[25, 'Aisha', 23, 'Godwin', 28, 'Victor', 18, 'Bianca', 25, 'Ada']

In [25]:
w.count(25)

2

# Tuple


- Ordered 
- Immutable
- Allows Duplicatate

In [26]:
t = ("Favour", 33, "Afe", 23)

In [ ]:
t.

# Set

- UNORDERED
- MUTABLE
- NO DUPLICATES

In [28]:
s = {"Ada", 23, "Viv", 23, "Godwin", 24, "Mercy", 25}

In [29]:
s

{23, 24, 25, 'Ada', 'Godwin', 'Mercy', 'Viv'}

In [30]:
s.add("TommyG")

In [31]:
type(s)

set

# Dictionary:

* if you want to create a table also known as data frame, we use dictionary.
- Ordered
- Mutable
-Keys Must be unique

In [54]:
d = {"Name": ["Afe", "Victor", "Sam", "Ada", "Bianca", "Faith", "Vivian", "Aisha"],
 "Age": [23, 26, 32, 25, 27, 25, 24,27],
 "Gender": ["Male", "Male", "Male", "Female", "Female", "Female", "Female", "Female"],
"Fav_course": [None, "Excel", None, "PowerBI", "SQL", "Python", None, "Tablue"]}

In [52]:
import pandas as pd

In [56]:
table = pd.DataFrame(d)

In [57]:
table

     Name  Age  Gender Fav_course
0     Afe   23    Male       None
1  Victor   26    Male      Excel
2     Sam   32    Male       None
3     Ada   25  Female    PowerBI
4  Bianca   27  Female        SQL
5   Faith   25  Female     Python
6  Vivian   24  Female       None
7   Aisha   27  Female     Tablue

In [ ]:
table.

In [38]:
print(d)

{'Name': ['Afe', 'Victor', 'Sam', 'Ada', 'Bianca', 'Faith', 'Vivian', 'Aisha'], 'Age': [23, 26, 32, 25, 27, 25, 24, 27], 'Gender': ['Male', 'Male', 'Male', 'Female', 'Female', 'Female', 'Female', 'Female'], 'Fav_course': [None, 'Excel', None, 'PowerBI', 'SQL', 'Python', None, 'Tablue']}

In [58]:
d["state"] = ["lagos", "Edo", "Abuja", "Kaduna", "jos", "Wuse", "Nasarawa", "Benue"]

In [59]:
d

{'Name': ['Afe', 'Victor', 'Sam', 'Ada', 'Bianca', 'Faith', 'Vivian', 'Aisha'],
 'Age': [23, 26, 32, 25, 27, 25, 24, 27],
 'Gender': ['Male',
  'Male',
  'Male',
  'Female',
  'Female',
  'Female',
  'Female',
  'Female'],
 'Fav_course': [None,
  'Excel',
  None,
  'PowerBI',
  'SQL',
  'Python',
  None,
  'Tablue'],
 'state': ['lagos',
  'Edo',
  'Abuja',
  'Kaduna',
  'jos',
  'Wuse',
  'Nasarawa',
  'Benue']}

In [41]:
print(d)

{'Name': ['Afe', 'Victor', 'Sam', 'Ada', 'Bianca', 'Faith', 'Vivian', 'Aisha'], 'Age': [23, 26, 32, 25, 27, 25, 24, 27], 'Gender': ['Male', 'Male', 'Male', 'Female', 'Female', 'Female', 'Female', 'Female'], 'Fav_course': [None, 'Excel', None, 'PowerBI', 'SQL', 'Python', None, 'Tablue'], 'state': ['lagos', 'Edo', 'Abuja', 'Kaduna']}

In [49]:
d.items()

dict_items([('Name', ['Afe', 'Victor', 'Sam', 'Ada', 'Bianca', 'Faith', 'Vivian', 'Aisha']), ('Age', [23, 26, 32, 25, 27, 25, 24, 27]), ('Gender', ['Male', 'Male', 'Male', 'Female', 'Female', 'Female', 'Female', 'Female']), ('Fav_course', [None, 'Excel', None, 'PowerBI', 'SQL', 'Python', None, 'Tablue']), ('state', ['lagos', 'Edo', 'Abuja', 'Kaduna'])])

In [50]:
import pandas as pd

In [60]:
pd.DataFrame(d)

     Name  Age  Gender Fav_course     state
0     Afe   23    Male       None     lagos
1  Victor   26    Male      Excel       Edo
2     Sam   32    Male       None     Abuja
3     Ada   25  Female    PowerBI    Kaduna
4  Bianca   27  Female        SQL       jos
5   Faith   25  Female     Python      Wuse
6  Vivian   24  Female       None  Nasarawa
7   Aisha   27  Female     Tablue     Benue

In [ ]:
import pan